import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Progress } from '@/components/ui/progress';
import { Badge } from '@/components/ui/badge';
import { Loader2, Bot, User, AlertTriangle } from 'lucide-react';
import { detectAI } from '@/utils/documentUtils';
import { useToast } from '@/hooks/use-toast';
import Header from './Header';
import Footer from './Footer';

const AIDetector = () => {
  const [text, setText] = useState('');
  const [analysis, setAnalysis] = useState<any>(null);
  const [isProcessing, setIsProcessing] = useState(false);
  const { toast } = useToast();

  const handleDetection = async () => {
    if (!text.trim()) {
      toast({
        title: "Error",
        description: "Please enter some text to analyze.",
        variant: "destructive",
      });
      return;
    }

    if (text.length < 50) {
      toast({
        title: "Text Too Short",
        description: "Please enter at least 50 characters for accurate detection.",
        variant: "destructive",
      });
      return;
    }

    setIsProcessing(true);
    try {
      const result = await detectAI(text);
      setAnalysis(result);
      toast({
        title: "Analysis Complete",
        description: "AI detection analysis has been completed.",
      });
    } catch (error) {
      toast({
        title: "Error",
        description: "Failed to analyze text. Please try again.",
        variant: "destructive",
      });
    } finally {
      setIsProcessing(false);
    }
  };

  const getConfidenceColor = (confidence: number) => {
    if (confidence > 80) return 'text-red-500';
    if (confidence > 60) return 'text-yellow-500';
    return 'text-green-500';
  };

  const getConfidenceLabel = (confidence: number) => {
    if (confidence > 80) return 'High';
    if (confidence > 60) return 'Medium';
    return 'Low';
  };

  return (
    <div className="min-h-screen bg-background">
      <Header />
      <main className="container mx-auto px-4 py-8">
        <div className="max-w-4xl mx-auto">
          <div className="text-center mb-8">
            <Bot className="w-16 h-16 mx-auto mb-4 text-primary" />
            <h1 className="text-4xl font-bold mb-4">AI Content Detector</h1>
            <p className="text-xl text-muted-foreground">
              Detect if text was generated by AI or written by humans using advanced analysis
            </p>
          </div>

          <div className="grid md:grid-cols-2 gap-6">
            <Card>
              <CardHeader>
                <CardTitle>Text to Analyze</CardTitle>
                <CardDescription>
                  Enter at least 50 characters for accurate AI detection
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <Textarea
                  placeholder="Paste the text you want to analyze here..."
                  value={text}
                  onChange={(e) => setText(e.target.value)}
                  className="min-h-[300px] resize-none"
                />
                <div className="flex justify-between items-center text-sm text-muted-foreground">
                  <span>Characters: {text.length}</span>
                  <span>Words: {text.split(' ').filter(word => word.length > 0).length}</span>
                </div>
                <Button 
                  onClick={handleDetection} 
                  disabled={isProcessing || text.length < 50}
                  className="w-full"
                >
                  {isProcessing ? (
                    <>
                      <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                      Analyzing Text...
                    </>
                  ) : (
                    'Detect AI Content'
                  )}
                </Button>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle>Detection Results</CardTitle>
                <CardDescription>
                  AI detection analysis and confidence score
                </CardDescription>
              </CardHeader>
              <CardContent>
                {analysis ? (
                  <div className="space-y-6">
                    <div className="text-center">
                      <div className="flex items-center justify-center mb-4">
                        {analysis.isAI ? (
                          <Bot className="w-12 h-12 text-red-500" />
                        ) : (
                          <User className="w-12 h-12 text-green-500" />
                        )}
                      </div>
                      <h3 className="text-2xl font-bold mb-2">
                        {analysis.isAI ? 'AI Generated' : 'Human Written'}
                      </h3>
                      <Badge 
                        variant={analysis.isAI ? 'destructive' : 'secondary'}
                        className="text-lg px-4 py-2"
                      >
                        {analysis.confidence}% Confidence
                      </Badge>
                    </div>

                    <div className="space-y-3">
                      <div className="flex justify-between items-center">
                        <span className="font-medium">Confidence Level:</span>
                        <span className={`font-bold ${getConfidenceColor(analysis.confidence)}`}>
                          {getConfidenceLabel(analysis.confidence)}
                        </span>
                      </div>
                      <Progress value={analysis.confidence} className="h-3" />
                    </div>

                    <Card className="border-l-4 border-l-blue-500">
                      <CardContent className="pt-4">
                        <div className="flex items-start gap-2">
                          <AlertTriangle className="w-5 h-5 text-blue-500 mt-0.5 flex-shrink-0" />
                          <div>
                            <h4 className="font-semibold mb-2">Analysis Summary</h4>
                            <p className="text-sm text-muted-foreground">
                              {analysis.analysis}
                            </p>
                          </div>
                        </div>
                      </CardContent>
                    </Card>

                    <div className="text-xs text-muted-foreground p-3 bg-muted rounded-lg">
                      <strong>Disclaimer:</strong> This tool provides AI detection estimates based on text patterns and characteristics. 
                      Results are not 100% accurate and should be used as a guide rather than definitive proof.
                    </div>
                  </div>
                ) : (
                  <div className="min-h-[300px] flex items-center justify-center text-muted-foreground">
                    <div className="text-center">
                      <Bot className="w-16 h-16 mx-auto mb-4 opacity-50" />
                      <p>Analysis results will appear here</p>
                    </div>
                  </div>
                )}
              </CardContent>
            </Card>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default AIDetector;